### PR TITLE
WIP: Mass matrix support for rosenbrock23

### PR DESCRIPTION
**Pull request by tshort**
This adds support for models with a `mass_matrix`. For me, this is to enable usage with models generated by ModelingToolkit. Right now, these models do not solve correctly.

I've marked it as WIP because I'm new to the code and probably need feedback on tests or anything else I need to do.

### CODE REVIEW

**Comment by tshort** [comment]
i removed the WIP because I'm not currently working on any changes. That was mainly to indicate it needs a good review.

**Review by utkarsh530 — APPROVED** [review]

**Comment by utkarsh530** [comment]
LGTM. Test failure looks unreal.

**Comment by utkarsh530** [comment]
Can you format your code?
```julia
using JuliaFormatter
format(".")
```

**Comment by ChrisRackauckas** [comment]
The test failures look pretty real. I'm not sure the uniform scaling kernels work on GPU.

**Comment by utkarsh530** [comment]
The test failures were due to double precision values with backends other than CUDA.

**Pull request merged**
