### PR TITLE
Use JuliaGPU's GitLab CI setup

### PR DESCRIPTION
**Pull request by christopher-dG**

### CODE REVIEW

**Comment by christopher-dG** [comment]
This one should be straightforward, since there are no extra test dependencies to fiddle with.

**Comment by christopher-dG** [comment]
Retried CI with a 3 hour timeout, maybe it'll go through this time.

**Comment by christopher-dG** [comment]
And of course, this time it works in less than 1h 😅 This is good to go now.

**Comment by ChrisRackauckas** [comment]
We probably need to put ourselves in a queue where whatever thing that has absolutely no GPU memory left is excluded. We can figure that out over time though.

**Pull request merged**
