### PR TITLE
Test v1.9

### PR DESCRIPTION
**Pull request by utkarsh530**

### CODE REVIEW

**Comment by utkarsh530** [comment]
@ChrisRackauckas I think `Linearsolve.jl` caused a breaking change here: https://buildkite.com/julialang/diffeqgpu-dot-jl/builds/510#01862989-6e8e-4cc1-aacb-c98e5d87438e/467-1011

**Comment by ChrisRackauckas** [comment]
@vpuri3

**Comment by vpuri3** [comment]
just got home. lemme take a look!

**Comment by vpuri3** [comment]
@ChrisRackauckas can i make edits to this PR?

**Comment by vpuri3** [comment]
@utkarsh530 , in the failing test, https://github.com/SciML/DiffEqGPU.jl/blob/ec7d40987bd1e478eb64917bb9574fe29c3f09b6/test/ensemblegpuarray.jl#L71, DiffEqGPU is passing a `size(W) = (3, 3, 10)` LHS and `_vec(linsolve_tmp) |> size = (30,)` RHS array to LinearSolve. This leads to errors in the actual solve:

```julia
julia> using LinearSolve; W = rand(3,3,10); b=rand(30); prob = LinearProblem(W,b); solve(prob)                                                                               [ Info: Precompiling LinearSolve [7ed4a6bd-45f5-4d41-b270-4a48e9bafcae]                
ERROR: Inconsistent problem size
Stacktrace:                                                                            
  [1] error(s::String)                                                                 
    @ Base ./error.jl:35                                                                 
[2] gmres!(solver::Krylov.GmresSolver{Float64, Float64, Vector{Float64}}, A::Array{Float64, 3}, b::Vector{Float64}; M::LinearAlgebra.UniformScaling{Bool}, N::LinearAlgebra.
UniformScaling{Bool}, ldiv::Bool, restart::Bool, reorthogonalization::Bool, atol::Float
64, rtol::Float64, itmax::Int64, verbose::Int64, history::Bool, callback::Krylov.var"#159#161", iostream::Core.CoreSTDOUT)                                                    
    @ Krylov ~/.julia/packages/Krylov/0FaHW/src/gmres.jl:108
  [3] #solve!#69                                                                       ```

**Comment by utkarsh530** [comment]
It uses the special linear solver here: https://github.com/SciML/DiffEqGPU.jl/blob/ec7d40987bd1e478eb64917bb9574fe29c3f09b6/src/DiffEqGPU.jl#L728

**Comment by vpuri3** [comment]
ok, then https://github.com/SciML/SciMLOperators.jl/pull/149 should this issue.

**Pull request closed without merging**
